### ISSUE TITLE
Crashes when clicking in node area frequently

### ISSUE THREAD

**Issue by dvn0** [phase1geo/Minder#110] opened 2020-01-09 22:26 UTC
Crashing when clicking anywhere in main node/edit area, pretty frequently. Only getting this after upgrading to 1.6.0. 

```
(minder:14133): GLib-GIO-ERROR **: 23:23:57.447: Settings schema 'com.github.phase1geo.minder' does not contain a key named 'auto-parse-embedded-urls'
[1]    14133 trace trap (core dumped)  minder
```

**Comment by phase1geo** [comment] 2020-01-10 01:20
Hmmm.  That gsetting value is defined within the com.github.phase1geo.minder.gschema.xml file.  Can you confirm that the file:

/usr/share/glib-2.0/schemas/com.github.phase1geo.minder.gschema.xml

Contains the string "auto-parse-embedded-urls"?  If you don't know how to do this, just send me the output of the terminal command:

grep auto-parse-embedded-urls /usr/share/glib-2.0/schemas/com.github.phase1geo.minder.gschema.xml

**Comment by phase1geo** [comment] 2020-02-29 23:32
I believe that this is a user issue caused by installing Minder incorrectly.  I may address this issue in the future if I can get some questions asked.  Until then I am deferring this bug fix.

**Comment by phase1geo** [comment] 2020-05-20 04:50
There hasn't been any activity on this issue for quite some time.  Closing issue to as I believe this problem was an installation issue. If this is incorrect and is still an ongoing issue, feel free to reopen this issue or open a new one.

**Closed by phase1geo** 2020-05-20 04:50 UTC
Labels: deferred
