### ISSUE TITLE
does not start on Manjaro since yesterday

### ISSUE THREAD

**Issue by cyricium** [phase1geo/Minder#321] opened 2021-03-27 05:49 UTC
Hello, 
first, thank you for this application. :-)
below the logs : 

  mars 27 06:34:59 prismordix audit[1]: SERVICE_START pid=1 uid=0 auid=4294967295 ses=4294967295 subj==unconfined msg='unit=systemd-coredump@4-6629-0 comm="systemd" exe="/usr/lib/systemd/systemd" hostname=? addr=? terminal=? res=success'
  mars 27 06:35:00 prismordix systemd-coredump[6630]: Process 6621 (com.github.phas) of user 1000 dumped core.
                                                      
                                                      Stack trace of thread 6621:
                                                      #0  0x00007f5b3aaafef5 raise (libc.so.6 + 0x3cef5)
                                                      #1  0x00007f5b3aa99862 abort (libc.so.6 + 0x26862)
                                                      #2  0x00007f5b3aaf1f38 __libc_message (libc.so.6 + 0x7ef38)
                                                      #3  0x00007f5b3aaf9bea malloc_printerr (libc.so.6 + 0x86bea)
                                                      #4  0x00007f5b3aafb470 _int_free (libc.so.6 + 0x88470)
                                                      #5  0x00007f5b3aafeca8 __libc_free (libc.so.6 + 0x8bca8)
                                                      #6  0x00005600f75ba701 n/a (com.github.phase1geo.minder + 0xdc701)
                                                      #7  0x00005600f75baeb2 n/a (com.github.phase1geo.minder + 0xdceb2)
                                                      #8  0x00005600f75bb1ba n/a (com.github.phase1geo.minder + 0xdd1ba)
                                                      #9  0x00007f5b3bf2f072 g_closure_invoke (libgobject-2.0.so.0 + 0x13072)
                                                      #10 0x00007f5b3bf57a85 n/a (libgobject-2.0.so.0 + 0x3ba85)
                                                      #11 0x00007f5b3bf4b5dd g_signal_emit_valist (libgobject-2.0.so.0 + 0x2f5dd)
                                                      #12 0x00007f5b3bf4bb40 g_signal_emit (libgobject-2.0.so.0 + 0x2fb40)
                                                      #13 0x00005600f7586b5b n/a (com.github.phase1geo.minder + 0xa8b5b)
                                                      #14 0x00005600f753218d n/a (com.github.phase1geo.minder + 0x5418d)
                                                      #15 0x00007f5b3bf2f072 g_closure_invoke (libgobject-2.0.so.0 + 0x13072)
                                                      #16 0x00007f5b3bf57a85 n/a (libgobject-2.0.so.0 + 0x3ba85)
                                                      #17 0x00007f5b3bf4b5dd g_signal_emit_valist (libgobject-2.0.so.0 + 0x2f5dd)
                                                      #18 0x00007f5b3bf4bb40 g_signal_emit (libgobject-2.0.so.0 + 0x2fb40)
                                                      #19 0x00007f5b3b13f0ae g_application_register (libgio-2.0.so.0 + 0xcc0ae)
                                                      #20 0x00007f5b3b13fa1c n/a (libgio-2.0.so.0 + 0xcca1c)
                                                      #21 0x00007f5b3b13fd7a g_application_run (libgio-2.0.so.0 + 0xccd7a)
                                                      #22 0x00005600f74f5d61 n/a (com.github.phase1geo.minder + 0x17d61)
                                                      #23 0x00007f5b3aa9ab25 __libc_start_main (libc.so.6 + 0x27b25)
                                                      #24 0x00005600f74f5e7e n/a (com.github.phase1geo.minder + 0x17e7e)
                                                      
                                                      Stack trace of thread 6624:
                                                      #0  0x00007f5b3ab6737f __poll (libc.so.6 + 0xf437f)
                                                      #1  0x00007f5b3be8ebaf n/a (libglib-2.0.so.0 + 0xa7baf)
                                                      #2  0x00007f5b3be393b1 g_main_context_iteration (libglib-2.0.so.0 + 0x523b1)
                                                      #3  0x00007f5b365f7ebe n/a (libdconfsettings.so + 0x5ebe)
                                                      #4  0x00007f5b3be67fc1 n/a (libglib-2.0.so.0 + 0x80fc1)
                                                      #5  0x00007f5b3a9db299 start_thread (libpthread.so.0 + 0x9299)
                                                      #6  0x00007f5b3ab72053 __clone (libc.so.6 + 0xff053)
                                                      
                                                      Stack trace of thread 6625:
                                                      #0  0x00007f5b3ab6ca9d syscall (libc.so.6 + 0xf9a9d)
                                                      #1  0x00007f5b3be87c5b g_cond_wait_until (libglib-2.0.so.0 + 0xa0c5b)
                                                      #2  0x00007f5b3be0a923 n/a (libglib-2.0.so.0 + 0x23923)
                                                      #3  0x00007f5b3be6afcb n/a (libglib-2.0.so.0 + 0x83fcb)
                                                      #4  0x00007f5b3be67fc1 n/a (libglib-2.0.so.0 + 0x80fc1)
                                                      #5  0x00007f5b3a9db299 start_thread (libpthread.so.0 + 0x9299)
                                                      #6  0x00007f5b3ab72053 __clone (libc.so.6 + 0xff053)
                                                      
                                                      Stack trace of thread 6622:
                                                      #0  0x00007f5b3ab6737f __poll (libc.so.6 + 0xf437f)
                                                      #1  0x00007f5b3be8ebaf n/a (libglib-2.0.so.0 + 0xa7baf)
                                                      #2  0x00007f5b3be393b1 g_main_context_iteration (libglib-2.0.so.0 + 0x523b1)
                                                      #3  0x00007f5b3be39402 n/a (libglib-2.0.so.0 + 0x52402)
                                                      #4  0x00007f5b3be67fc1 n/a (libglib-2.0.so.0 + 0x80fc1)
                                                      #5  0x00007f5b3a9db299 start_thread (libpthread.so.0 + 0x9299)
                                                      #6  0x00007f5b3ab72053 __clone (libc.so.6 + 0xff053)
                                                      
                                                      Stack trace of thread 6626:
                                                      #0  0x00007f5b3ab6ca9d syscall (libc.so.6 + 0xf9a9d)
                                                      #1  0x00007f5b3be87c5b g_cond_wait_until (libglib-2.0.so.0 + 0xa0c5b)
                                                      #2  0x00007f5b3be0a923 n/a (libglib-2.0.so.0 + 0x23923)
                                                      #3  0x00007f5b3be6afcb n/a (libglib-2.0.so.0 + 0x83fcb)
                                                      #4  0x00007f5b3be67fc1 n/a (libglib-2.0.so.0 + 0x80fc1)
                                                      #5  0x00007f5b3a9db299 start_thread (libpthread.so.0 + 0x9299)
                                                      #6  0x00007f5b3ab72053 __clone (libc.so.6 + 0xff053)
                                                      
                                                      Stack trace of thread 6623:
                                                      #0  0x00007f5b3ab6737f __poll (libc.so.6 + 0xf437f)
                                                      #1  0x00007f5b3be8ebaf n/a (libglib-2.0.so.0 + 0xa7baf)
                                                      #2  0x00007f5b3be3a0d3 g_main_loop_run (libglib-2.0.so.0 + 0x530d3)
                                                      #3  0x00007f5b3b174d18 n/a (libgio-2.0.so.0 + 0x101d18)
                                                      #4  0x00007f5b3be67fc1 n/a (libglib-2.0.so.0 + 0x80fc1)
                                                      #5  0x00007f5b3a9db299 start_thread (libpthread.so.0 + 0x9299)
                                                      #6  0x00007f5b3ab72053 __clone (libc.so.6 + 0xff053)
  mars 27 06:35:00 prismordix systemd[1]: systemd-coredump@4-6629-0.service: Succeeded.
  mars 27 06:35:00 prismordix kernel: audit: type=1131 audit(1616823300.313:184): pid=1 uid=0 auid=4294967295 ses=4294967295 subj==unconfined msg='unit=systemd-coredump@4-6629-0 comm="systemd" exe="/usr/lib/systemd/systemd" hostname=? addr=? terminal=? res=success'
  mars 27 06:35:00 prismordix audit[1]: SERVICE_STOP pid=1 uid=0 auid=4294967295 ses=4294967295 subj==unconfined msg='unit=systemd-coredump@4-6629-0 comm="systemd" exe="/usr/lib/systemd/systemd" hostname=? addr=? terminal=? res=success'
  mars 27 06:35:00 prismordix audit: BPF prog-id=24 op=UNLOAD
  mars 27 06:35:00 prismordix audit: BPF prog-id=23 op=UNLOAD
  mars 27 06:35:00 prismordix kernel: audit: type=1334 audit(1616823300.390:185): prog-id=24 op=UNLOAD
  mars 27 06:35:00 prismordix kernel: audit: type=1334 audit(1616823300.390:186): prog-id=23 op=UNLOAD

**Comment by cyricium** [comment] 2021-04-03 06:43
> Same with me too (in Arch-based distro).



Yes, it's true that we share the same package manager. I sent a mail to the guy who compiled Minder for Arch and he answered that it has nothing to do with Manjaro ...

What's annoying is that I don't see any other alternative to Minder to open existing .minder files.

**Comment by Bernd-L** [comment] 2021-04-05 19:39
For anyone who needs it:

# Workaround

1. Install downgrade: `pamac install downgrade` according to [the guide](https://wiki.manjaro.org/index.php/Downgrading_packages) 
2. Run `sudo DOWNGRADE_FROM_ALA=1 downgrade minder`
3. When asked, enter "2" to select `2)  minder    1.11.3  1  x86_64  (remote)`
4. Press enter to reject ignoring minder

---

Hope this helps someone :shrug:

**Comment by cyricium** [comment] 2021-04-05 20:21
Hello Bernd-L

Great idea ! 

Thanks but at the last step of selecting `2) minder 1.11.3 1 x86_64 (remote)`, the system returns :

`error: '/var/cache/pacman/pkg/minder-1.12.0-1-x86_64.pkg.tar.zst': package for which the required signature is missing`

**Comment by eXConf** [comment] 2021-04-06 19:51
As a sort of another workaround - there is working [flatpack package](https://flathub.org/apps/details/com.github.phase1geo.minder) of Minder.

**Comment by cyricium** [comment] 2021-04-06 20:30
> As a sort of another workaround - there is working [flatpak package](https://flathub.org/apps/details/com.github.phase1geo.minder) of Minder.

Thank you very much @eXConf, 
Respect : It works :-D

I would be curious to know what happened.
I see that I'm on Linux kernel 5.9.16-1 but the recommended LTS kernel is 5.4.105-1.
Is this maybe it?

**Comment by shadear-bakr** [comment] 2021-04-11 18:48
I have the same problem, and I am on Linux kernel 5.11.10-1, if that helps?
The flatpak workaround works, thanks.

**Comment by cyricium** [comment] 2021-04-11 20:30
Thank you @shadear-bakr ,
I think we have the understanding of the problem and the solution

**Comment by phase1geo** [comment] 2021-04-15 03:18
I believe that this issue is a duplicate of #318 .  I believe that the master branch contains fixes for this issue.  If someone on this thread would like to verify the fix, I would appreciate that.

**Comment by phase1geo** [comment] 2021-04-16 11:55
I have released 1.12.1 that should fix this issue. Closing bug.

**Closed by phase1geo** 2021-04-16 11:55 UTC
Labels: duplicate
