### ISSUE TITLE
Read-only files support (mistaken warning about external changes)

### ISSUE THREAD

**Issue by nekohayo** [phase1geo/Minder#540] opened 2023-04-06 04:13 UTC
I'm running 1.14.0 on Fedora 37-38.

After I'm done designing mind maps, I sometimes set some of my saved .minder files as read-only on the filesystem, for safety and to avoid any handling accidents while viewing them later on.

However, it seems Minder gets confused about this. When you open such a file, as soon as you pan/move around the graph, you will get a dialog prompt that says:

> # Overwrite or reload?
> 
> The file some_long_path/foo.minder was modified outside of the application.
> 
> What do you want to do?
> 
> [Discard changes and reload] [Save local version and overwrite]

Even if I click "Discard changes and reload", as soon as I pan around again, the dialog reappears, which tells me it's a bug rather than me having had some mismatching changes.

Ideally Minder should handle read-only files properly, and allow some basic actions, but saving any changes would require either the file to be set read+write externally (minder could monitor for that, maybe with inotify?) or force the user to go through the "Save As..." action instead of a regular overwrite save.

**Comment by phase1geo** [comment] 2023-04-09 13:19
This issue is caused by #503.

**Comment by phase1geo** [comment] 2023-04-15 03:18
I have merged the issue branch into the master branch.  Here is a summary of the changes:

1. If an autosave fails (in this case, due to the permissions being readonly), we will restore the original etag associated with the readonly file so that we don't falsely detected that the readonly file changed (which it didn't).

2. We will display the readonly status of the current file in the titlebar and update it if it changes.

3. If a file was previously detected as readonly but becomes writeable and the associated mindmap contains changes in the application, the changes will be autosaved to the file once more.

Feel free to grab the master branch and give it a try.

**Closed** 2023-04-24 12:11 UTC
Labels: bug, duplicate, fixed
