### ISSUE TITLE
Error during build 1.7.0

### ISSUE THREAD

**Issue by tim77** [phase1geo/Minder#122] opened 2020-03-21 16:52 UTC
Hello. New `1.7.0` won't compile. What i am missing here?

Tried with `Vala 0.46.6` and latest `Vala 0.48` version. OS - Fedora 31-33.

```vala
[6/151] valac -C --define=GTK322 --vapidir /builddir/build/BUILD/Minder-1.7.0/vapi --pkg gtksourceview-3.0 --pkg libarchive --pkg libxml-2.0 --pkg gtk+-3.0 --pkg granite --pkg gee-0.8 --pkg cairo --pkg glib-2.0 --pkg gobject-2.0 --color=always --directory com.github.phase1geo.minder@exe --basedir ../ --gresources=../data/com.github.phase1geo.minder.gresource.xml /builddir/build/BUILD/Minder-1.7.0/vapi/libmarkdown.vapi ../src/animator/AnimatorAction.vala ../src/animator/AnimatorNodes.vala ../src/animator/AnimatorPan.vala ../src/animator/AnimatorPanScale.vala ../src/animator/AnimatorPositions.vala ../src/animator/AnimatorScale.vala ../src/exports/ExportCSV.vala ../src/exports/ExportFreemind.vala ../src/exports/ExportFreeplane.vala ../src/exports/ExportImage.vala ../src/exports/ExportMarkdown.vala ../src/exports/ExportMermaid.vala ../src/exports/ExportOPML.vala ../src/exports/ExportOrgMode.vala ../src/exports/ExportOutliner.vala ../src/exports/ExportPDF.vala ../src/exports/ExportPNG.vala ../src/exports/ExportPortableMinder.vala ../src/exports/ExportPrint.vala ../src/exports/ExportSVG.vala ../src/exports/ExportText.vala ../src/exports/ExportYed.vala ../src/layouts/LayoutDown.vala ../src/layouts/LayoutHorizontal.vala ../src/layouts/LayoutLeft.vala ../src/layouts/LayoutManual.vala ../src/layouts/LayoutRight.vala ../src/layouts/LayoutUp.vala ../src/layouts/LayoutVertical.vala ../src/styles/LinkTypeCurved.vala ../src/styles/LinkTypeSquared.vala ../src/styles/LinkTypeStraight.vala ../src/styles/NodeBorderBracket.vala ../src/styles/NodeBorderNone.vala ../src/styles/NodeBorderPill.vala ../src/styles/NodeBorderRounded.vala ../src/styles/NodeBorderSquared.vala ../src/styles/NodeBorderUnderlined.vala ../src/themes/ThemeDark.vala ../src/themes/ThemeDefault.vala ../src/themes/ThemeSolarizedDark.vala ../src/themes/ThemeSolarizedLight.vala ../src/undo_actions/UndoConnectionAdd.vala ../src/undo_actions/UndoConnectionChange.vala ../src/undo_actions/UndoConnectionColor.vala ../src/undo_actions/UndoConnectionDelete.vala ../src/undo_actions/UndoConnectionNote.vala ../src/undo_actions/UndoConnectionTitle.vala ../src/undo_actions/UndoConnectionsDelete.vala ../src/undo_actions/UndoNodeAddParent.vala ../src/undo_actions/UndoNodeAttach.vala ../src/undo_actions/UndoNodeBalance.vala ../src/undo_actions/UndoNodeCut.vala ../src/undo_actions/UndoNodeDelete.vala ../src/undo_actions/UndoNodeDetach.vala ../src/undo_actions/UndoNodeFold.vala ../src/undo_actions/UndoNodeFoldChanges.vala ../src/undo_actions/UndoNodeImage.vala ../src/undo_actions/UndoNodeInsert.vala ../src/undo_actions/UndoNodeLayout.vala ../src/undo_actions/UndoNodeLink.vala ../src/undo_actions/UndoNodeLinkColor.vala ../src/undo_actions/UndoNodeMove.vala ../src/undo_actions/UndoNodeName.vala ../src/undo_actions/UndoNodeNote.vala ../src/undo_actions/UndoNodePaste.vala ../src/undo_actions/UndoNodeReparentLinkColor.vala ../src/undo_actions/UndoNodeResize.vala ../src/undo_actions/UndoNodeReveal.vala ../src/undo_actions/UndoNodeSort.vala ../src/undo_actions/UndoNodeTask.vala ../src/undo_actions/UndoNodesCut.vala ../src/undo_actions/UndoNodesDelete.vala ../src/undo_actions/UndoNodesFold.vala ../src/undo_actions/UndoNodesInsert.vala ../src/undo_actions/UndoNodesLink.vala ../src/undo_actions/UndoNodesLinkColor.vala ../src/undo_actions/UndoNodesRandLinkColor.vala ../src/undo_actions/UndoNodesReparentLinkColor.vala ../src/undo_actions/UndoStyleAffectChange.vala ../src/undo_actions/UndoStyleChange.vala ../src/undo_actions/UndoStyleConnectionArrow.vala ../src/undo_actions/UndoStyleConnectionDash.vala ../src/undo_actions/UndoStyleConnectionFont.vala ../src/undo_actions/UndoStyleConnectionPadding.vala ../src/undo_actions/UndoStyleConnectionWidth.vala ../src/undo_actions/UndoStyleLinkArrow.vala ../src/undo_actions/UndoStyleLinkDash.vala ../src/undo_actions/UndoStyleLinkType.vala ../src/undo_actions/UndoStyleLinkWidth.vala ../src/undo_actions/UndoStyleNodeBorder.vala ../src/undo_actions/UndoStyleNodeBorderwidth.vala ../src/undo_actions/UndoStyleNodeFill.vala ../src/undo_actions/UndoStyleNodeFont.vala ../src/undo_actions/UndoStyleNodeMargin.vala ../src/undo_actions/UndoStyleNodeMarkup.vala ../src/undo_actions/UndoStyleNodePadding.vala ../src/Animator.vala ../src/Application.vala ../src/Bezier.vala ../src/CanvasText.vala ../src/Connection.vala ../src/ConnectionInspector.vala ../src/ConnectionMenu.vala ../src/Connections.vala ../src/ConnectionsMenu.vala ../src/CurrentInspector.vala ../src/Document.vala ../src/DrawArea.vala ../src/DynamicNotebook.vala ../src/EmptyInspector.vala ../src/EmptyMenu.vala ../src/ImageEditor.vala ../src/ImageManager.vala ../src/Layout.vala ../src/Layouts.vala ../src/LinkDash.vala ../src/LinkType.vala ../src/MainWindow.vala ../src/MapInspector.vala ../src/Node.vala ../src/NodeBorder.vala ../src/NodeImage.vala ../src/NodeInspector.vala ../src/NodeMenu.vala ../src/NodesMenu.vala ../src/NoteView.vala ../src/Partitioner.vala ../src/QuickEntry.vala ../src/Selection.vala ../src/Style.vala ../src/StyleInspector.vala ../src/Styles.vala ../src/TextMenu.vala ../src/Theme.vala ../src/ThemeEditor.vala ../src/Themes.vala ../src/UndoBuffer.vala ../src/UndoItem.vala ../src/UrlEditor.vala ../src/UrlLinks.vala ../src/Utils.vala ../tests/assert.vala ../tests/test.vala
FAILED: com.github.phase1geo.minder@exe/src/animator/AnimatorAction.c com.github.phase1geo.minder@exe/src/animator/AnimatorNodes.c com.github.phase1geo.minder@exe/src/animator/AnimatorPan.c com.github.phase1geo.minder@exe/src/animator/AnimatorPanScale.c com.github.phase1geo.minder@exe/src/animator/AnimatorPositions.c com.github.phase1geo.minder@exe/src/animator/AnimatorScale.c com.github.phase1geo.minder@exe/src/exports/ExportCSV.c com.github.phase1geo.minder@exe/src/exports/ExportFreemind.c com.github.phase1geo.minder@exe/src/exports/ExportFreeplane.c com.github.phase1geo.minder@exe/src/exports/ExportImage.c com.github.phase1geo.minder@exe/src/exports/ExportMarkdown.c com.github.phase1geo.minder@exe/src/exports/ExportMermaid.c com.github.phase1geo.minder@exe/src/exports/ExportOPML.c com.github.phase1geo.minder@exe/src/exports/ExportOrgMode.c com.github.phase1geo.minder@exe/src/exports/ExportOutliner.c com.github.phase1geo.minder@exe/src/exports/ExportPDF.c com.github.phase1geo.minder@exe/src/exports/ExportPNG.c com.github.phase1geo.minder@exe/src/exports/ExportPortableMinder.c com.github.phase1geo.minder@exe/src/exports/ExportPrint.c com.github.phase1geo.minder@exe/src/exports/ExportSVG.c com.github.phase1geo.minder@exe/src/exports/ExportText.c com.github.phase1geo.minder@exe/src/exports/ExportYed.c com.github.phase1geo.minder@exe/src/layouts/LayoutDown.c com.github.phase1geo.minder@exe/src/layouts/LayoutHorizontal.c com.github.phase1geo.minder@exe/src/layouts/LayoutLeft.c com.github.phase1geo.minder@exe/src/layouts/LayoutManual.c com.github.phase1geo.minder@exe/src/layouts/LayoutRight.c com.github.phase1geo.minder@exe/src/layouts/LayoutUp.c com.github.phase1geo.minder@exe/src/layouts/LayoutVertical.c com.github.phase1geo.minder@exe/src/styles/LinkTypeCurved.c com.github.phase1geo.minder@exe/src/styles/LinkTypeSquared.c com.github.phase1geo.minder@exe/src/styles/LinkTypeStraight.c com.github.phase1geo.minder@exe/src/styles/NodeBorderBracket.c com.github.phase1geo.minder@exe/src/styles/NodeBorderNone.c com.github.phase1geo.minder@exe/src/styles/NodeBorderPill.c com.github.phase1geo.minder@exe/src/styles/NodeBorderRounded.c com.github.phase1geo.minder@exe/src/styles/NodeBorderSquared.c com.github.phase1geo.minder@exe/src/styles/NodeBorderUnderlined.c com.github.phase1geo.minder@exe/src/themes/ThemeDark.c com.github.phase1geo.minder@exe/src/themes/ThemeDefault.c com.github.phase1geo.minder@exe/src/themes/ThemeSolarizedDark.c com.github.phase1geo.minder@exe/src/themes/ThemeSolarizedLight.c com.github.phase1geo.minder@exe/src/undo_actions/UndoConnectionAdd.c com.github.phase1geo.minder@exe/src/undo_actions/UndoConnectionChange.c com.github.phase1geo.minder@exe/src/undo_actions/UndoConnectionColor.c com.github.phase1geo.minder@exe/src/undo_actions/UndoConnectionDelete.c com.github.phase1geo.minder@exe/src/undo_actions/UndoConnectionNote.c com.github.phase1geo.minder@exe/src/undo_actions/UndoConnectionTitle.c com.github.phase1geo.minder@exe/src/undo_actions/UndoConnectionsDelete.c com.github.phase1geo.minder@exe/src/undo_actions/UndoNodeAddParent.c com.github.phase1geo.minder@exe/src/undo_actions/UndoNodeAttach.c com.github.phase1geo.minder@exe/src/undo_actions/UndoNodeBalance.c com.github.phase1geo.minder@exe/src/undo_actions/UndoNodeCut.c com.github.phase1geo.minder@exe/src/undo_actions/UndoNodeDelete.c com.github.phase1geo.minder@exe/src/undo_actions/UndoNodeDetach.c com.github.phase1geo.minder@exe/src/undo_actions/UndoNodeFold.c com.github.phase1geo.minder@exe/src/undo_actions/UndoNodeFoldChanges.c com.github.phase1geo.minder@exe/src/undo_actions/UndoNodeImage.c com.github.phase1geo.minder@exe/src/undo_actions/UndoNodeInsert.c com.github.phase1geo.minder@exe/src/undo_actions/UndoNodeLayout.c com.github.phase1geo.minder@exe/src/undo_actions/UndoNodeLink.c com.github.phase1geo.minder@exe/src/undo_actions/UndoNodeLinkColor.c com.github.phase1geo.minder@exe/src/undo_actions/UndoNodeMove.c com.github.phase1geo.minder@exe/src/undo_actions/UndoNodeName.c com.github.phase1geo.minder@exe/src/undo_actions/UndoNodeNote.c com.github.phase1geo.minder@exe/src/undo_actions/UndoNodePaste.c com.github.phase1geo.minder@exe/src/undo_actions/UndoNodeReparentLinkColor.c com.github.phase1geo.minder@exe/src/undo_actions/UndoNodeResize.c com.github.phase1geo.minder@exe/src/undo_actions/UndoNodeReveal.c com.github.phase1geo.minder@exe/src/undo_actions/UndoNodeSort.c com.github.phase1geo.minder@exe/src/undo_actions/UndoNodeTask.c com.github.phase1geo.minder@exe/src/undo_actions/UndoNodesCut.c com.github.phase1geo.minder@exe/src/undo_actions/UndoNodesDelete.c com.github.phase1geo.minder@exe/src/undo_actions/UndoNodesFold.c com.github.phase1geo.minder@exe/src/undo_actions/UndoNodesInsert.c com.github.phase1geo.minder@exe/src/undo_actions/UndoNodesLink.c com.github.phase1geo.minder@exe/src/undo_actions/UndoNodesLinkColor.c com.github.phase1geo.minder@exe/src/undo_actions/UndoNodesRandLinkColor.c com.github.phase1geo.minder@exe/src/undo_actions/UndoNodesReparentLinkColor.c com.github.phase1geo.minder@exe/src/undo_actions/UndoStyleAffectChange.c com.github.phase1geo.minder@exe/src/undo_actions/UndoStyleChange.c com.github.phase1geo.minder@exe/src/undo_actions/UndoStyleConnectionArrow.c com.github.phase1geo.minder@exe/src/undo_actions/UndoStyleConnectionDash.c com.github.phase1geo.minder@exe/src/undo_actions/UndoStyleConnectionFont.c com.github.phase1geo.minder@exe/src/undo_actions/UndoStyleConnectionPadding.c com.github.phase1geo.minder@exe/src/undo_actions/UndoStyleConnectionWidth.c com.github.phase1geo.minder@exe/src/undo_actions/UndoStyleLinkArrow.c com.github.phase1geo.minder@exe/src/undo_actions/UndoStyleLinkDash.c com.github.phase1geo.minder@exe/src/undo_actions/UndoStyleLinkType.c com.github.phase1geo.minder@exe/src/undo_actions/UndoStyleLinkWidth.c com.github.phase1geo.minder@exe/src/undo_actions/UndoStyleNodeBorder.c com.github.phase1geo.minder@exe/src/undo_actions/UndoStyleNodeBorderwidth.c com.github.phase1geo.minder@exe/src/undo_actions/UndoStyleNodeFill.c com.github.phase1geo.minder@exe/src/undo_actions/UndoStyleNodeFont.c com.github.phase1geo.minder@exe/src/undo_actions/UndoStyleNodeMargin.c com.github.phase1geo.minder@exe/src/undo_actions/UndoStyleNodeMarkup.c com.github.phase1geo.minder@exe/src/undo_actions/UndoStyleNodePadding.c com.github.phase1geo.minder@exe/src/Animator.c com.github.phase1geo.minder@exe/src/Application.c com.github.phase1geo.minder@exe/src/Bezier.c com.github.phase1geo.minder@exe/src/CanvasText.c com.github.phase1geo.minder@exe/src/Connection.c com.github.phase1geo.minder@exe/src/ConnectionInspector.c com.github.phase1geo.minder@exe/src/ConnectionMenu.c com.github.phase1geo.minder@exe/src/Connections.c com.github.phase1geo.minder@exe/src/ConnectionsMenu.c com.github.phase1geo.minder@exe/src/CurrentInspector.c com.github.phase1geo.minder@exe/src/Document.c com.github.phase1geo.minder@exe/src/DrawArea.c com.github.phase1geo.minder@exe/src/DynamicNotebook.c com.github.phase1geo.minder@exe/src/EmptyInspector.c com.github.phase1geo.minder@exe/src/EmptyMenu.c com.github.phase1geo.minder@exe/src/ImageEditor.c com.github.phase1geo.minder@exe/src/ImageManager.c com.github.phase1geo.minder@exe/src/Layout.c com.github.phase1geo.minder@exe/src/Layouts.c com.github.phase1geo.minder@exe/src/LinkDash.c com.github.phase1geo.minder@exe/src/LinkType.c com.github.phase1geo.minder@exe/src/MainWindow.c com.github.phase1geo.minder@exe/src/MapInspector.c com.github.phase1geo.minder@exe/src/Node.c com.github.phase1geo.minder@exe/src/NodeBorder.c com.github.phase1geo.minder@exe/src/NodeImage.c com.github.phase1geo.minder@exe/src/NodeInspector.c com.github.phase1geo.minder@exe/src/NodeMenu.c com.github.phase1geo.minder@exe/src/NodesMenu.c com.github.phase1geo.minder@exe/src/NoteView.c com.github.phase1geo.minder@exe/src/Partitioner.c com.github.phase1geo.minder@exe/src/QuickEntry.c com.github.phase1geo.minder@exe/src/Selection.c com.github.phase1geo.minder@exe/src/Style.c com.github.phase1geo.minder@exe/src/StyleInspector.c com.github.phase1geo.minder@exe/src/Styles.c com.github.phase1geo.minder@exe/src/TextMenu.c com.github.phase1geo.minder@exe/src/Theme.c com.github.phase1geo.minder@exe/src/ThemeEditor.c com.github.phase1geo.minder@exe/src/Themes.c com.github.phase1geo.minder@exe/src/UndoBuffer.c com.github.phase1geo.minder@exe/src/UndoItem.c com.github.phase1geo.minder@exe/src/UrlEditor.c com.github.phase1geo.minder@exe/src/UrlLinks.c com.github.phase1geo.minder@exe/src/Utils.c com.github.phase1geo.minder@exe/tests/assert.c com.github.phase1geo.minder@exe/tests/test.c 
valac -C --define=GTK322 --vapidir /builddir/build/BUILD/Minder-1.7.0/vapi --pkg gtksourceview-3.0 --pkg libarchive --pkg libxml-2.0 --pkg gtk+-3.0 --pkg granite --pkg gee-0.8 --pkg cairo --pkg glib-2.0 --pkg gobject-2.0 --color=always --directory com.github.phase1geo.minder@exe --basedir ../ --gresources=../data/com.github.phase1geo.minder.gresource.xml /builddir/build/BUILD/Minder-1.7.0/vapi/libmarkdown.vapi ../src/animator/AnimatorAction.vala ../src/animator/AnimatorNodes.vala ../src/animator/AnimatorPan.vala ../src/animator/AnimatorPanScale.vala ../src/animator/AnimatorPositions.vala ../src/animator/AnimatorScale.vala ../src/exports/ExportCSV.vala ../src/exports/ExportFreemind.vala ../src/exports/ExportFreeplane.vala ../src/exports/ExportImage.vala ../src/exports/ExportMarkdown.vala ../src/exports/ExportMermaid.vala ../src/exports/ExportOPML.vala ../src/exports/ExportOrgMode.vala ../src/exports/ExportOutliner.vala ../src/exports/ExportPDF.vala ../src/exports/ExportPNG.vala ../src/exports/ExportPortableMinder.vala ../src/exports/ExportPrint.vala ../src/exports/ExportSVG.vala ../src/exports/ExportText.vala ../src/exports/ExportYed.vala ../src/layouts/LayoutDown.vala ../src/layouts/LayoutHorizontal.vala ../src/layouts/LayoutLeft.vala ../src/layouts/LayoutManual.vala ../src/layouts/LayoutRight.vala ../src/layouts/LayoutUp.vala ../src/layouts/LayoutVertical.vala ../src/styles/LinkTypeCurved.vala ../src/styles/LinkTypeSquared.vala ../src/styles/LinkTypeStraight.vala ../src/styles/NodeBorderBracket.vala ../src/styles/NodeBorderNone.vala ../src/styles/NodeBorderPill.vala ../src/styles/NodeBorderRounded.vala ../src/styles/NodeBorderSquared.vala ../src/styles/NodeBorderUnderlined.vala ../src/themes/ThemeDark.vala ../src/themes/ThemeDefault.vala ../src/themes/ThemeSolarizedDark.vala ../src/themes/ThemeSolarizedLight.vala ../src/undo_actions/UndoConnectionAdd.vala ../src/undo_actions/UndoConnectionChange.vala ../src/undo_actions/UndoConnectionColor.vala ../src/undo_actions/UndoConnectionDelete.vala ../src/undo_actions/UndoConnectionNote.vala ../src/undo_actions/UndoConnectionTitle.vala ../src/undo_actions/UndoConnectionsDelete.vala ../src/undo_actions/UndoNodeAddParent.vala ../src/undo_actions/UndoNodeAttach.vala ../src/undo_actions/UndoNodeBalance.vala ../src/undo_actions/UndoNodeCut.vala ../src/undo_actions/UndoNodeDelete.vala ../src/undo_actions/UndoNodeDetach.vala ../src/undo_actions/UndoNodeFold.vala ../src/undo_actions/UndoNodeFoldChanges.vala ../src/undo_actions/UndoNodeImage.vala ../src/undo_actions/UndoNodeInsert.vala ../src/undo_actions/UndoNodeLayout.vala ../src/undo_actions/UndoNodeLink.vala ../src/undo_actions/UndoNodeLinkColor.vala ../src/undo_actions/UndoNodeMove.vala ../src/undo_actions/UndoNodeName.vala ../src/undo_actions/UndoNodeNote.vala ../src/undo_actions/UndoNodePaste.vala ../src/undo_actions/UndoNodeReparentLinkColor.vala ../src/undo_actions/UndoNodeResize.vala ../src/undo_actions/UndoNodeReveal.vala ../src/undo_actions/UndoNodeSort.vala ../src/undo_actions/UndoNodeTask.vala ../src/undo_actions/UndoNodesCut.vala ../src/undo_actions/UndoNodesDelete.vala ../src/undo_actions/UndoNodesFold.vala ../src/undo_actions/UndoNodesInsert.vala ../src/undo_actions/UndoNodesLink.vala ../src/undo_actions/UndoNodesLinkColor.vala ../src/undo_actions/UndoNodesRandLinkColor.vala ../src/undo_actions/UndoNodesReparentLinkColor.vala ../src/undo_actions/UndoStyleAffectChange.vala ../src/undo_actions/UndoStyleChange.vala ../src/undo_actions/UndoStyleConnectionArrow.vala ../src/undo_actions/UndoStyleConnectionDash.vala ../src/undo_actions/UndoStyleConnectionFont.vala ../src/undo_actions/UndoStyleConnectionPadding.vala ../src/undo_actions/UndoStyleConnectionWidth.vala ../src/undo_actions/UndoStyleLinkArrow.vala ../src/undo_actions/UndoStyleLinkDash.vala ../src/undo_actions/UndoStyleLinkType.vala ../src/undo_actions/UndoStyleLinkWidth.vala ../src/undo_actions/UndoStyleNodeBorder.vala ../src/undo_actions/UndoStyleNodeBorderwidth.vala ../src/undo_actions/UndoStyleNodeFill.vala ../src/undo_actions/UndoStyleNodeFont.vala ../src/undo_actions/UndoStyleNodeMargin.vala ../src/undo_actions/UndoStyleNodeMarkup.vala ../src/undo_actions/UndoStyleNodePadding.vala ../src/Animator.vala ../src/Application.vala ../src/Bezier.vala ../src/CanvasText.vala ../src/Connection.vala ../src/ConnectionInspector.vala ../src/ConnectionMenu.vala ../src/Connections.vala ../src/ConnectionsMenu.vala ../src/CurrentInspector.vala ../src/Document.vala ../src/DrawArea.vala ../src/DynamicNotebook.vala ../src/EmptyInspector.vala ../src/EmptyMenu.vala ../src/ImageEditor.vala ../src/ImageManager.vala ../src/Layout.vala ../src/Layouts.vala ../src/LinkDash.vala ../src/LinkType.vala ../src/MainWindow.vala ../src/MapInspector.vala ../src/Node.vala ../src/NodeBorder.vala ../src/NodeImage.vala ../src/NodeInspector.vala ../src/NodeMenu.vala ../src/NodesMenu.vala ../src/NoteView.vala ../src/Partitioner.vala ../src/QuickEntry.vala ../src/Selection.vala ../src/Style.vala ../src/StyleInspector.vala ../src/Styles.vala ../src/TextMenu.vala ../src/Theme.vala ../src/ThemeEditor.vala ../src/Themes.vala ../src/UndoBuffer.vala ../src/UndoItem.vala ../src/UrlEditor.vala ../src/UrlLinks.vala ../src/Utils.vala ../tests/assert.vala ../tests/test.vala
../src/exports/ExportPortableMinder.vala:71.23-71.42: error: Argument 1: Cannot convert from `int64' to `Archive.int64_t'
      entry.set_size( file_info.get_size() );
                      ^^^^^^^^^^^^^^^^^^^^
../src/exports/ExportPortableMinder.vala:72.27-72.45: error: Argument 1: Cannot convert from `uint' to `Archive.FileType'
      entry.set_filetype( (uint)Posix.S_IFREG );
                          ^^^^^^^^^^^^^^^^^^^
../src/exports/ExportPortableMinder.vala:91.9-91.48: error: 1 extra arguments for `ssize_t Archive.Write.write_data (uint8[])'
        archive.write_data( buffer, bytes_read );
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
../src/exports/ExportPortableMinder.vala:163.14-163.81: error: 1 extra arguments for `Archive.Result Archive.Read.read_data_block (out weak uint8[], out Archive.int64_t)'
      while( archive.read_data_block( out buffer, out buffer_length, out offset ) == Archive.Result.OK ) {
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
../src/exports/ExportPortableMinder.vala:164.41-164.46: error: Argument 1: Cannot convert from `void*' to `unowned uint8[]'
        if( extractor.write_data_block( buffer, buffer_length, offset ) != Archive.Result.OK ) {
                                        ^^^^^^
../src/exports/ExportPortableMinder.vala:164.13-164.71: error: 1 extra arguments for `ssize_t Archive.Write.write_data_block (uint8[], Archive.int64_t)'
        if( extractor.write_data_block( buffer, buffer_length, offset ) != Archive.Result.OK ) {
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```

**Comment by phase1geo** [comment] 2020-03-21 17:08
What version of libarchive-dev are you using?

**Comment by tim77** [comment] 2020-03-21 17:10
> What version of libarchive-dev are you using?

`3.4.2`

**Comment by phase1geo** [comment] 2020-03-21 18:43
I work in elementary OS which appears to be using older versions of some tools:

libarchive-dev 3.2.2
valac 0.40.19

I'm not sure if this is just a type casting issue or if there is more that would need to be updated to get this to work in your environment.  I'll look into it, but I need to make sure that things remain working for elementary builds.

**Comment by tim77** [comment] 2020-03-21 18:45
Sure, thanks! Hope this helpful bug report.

**Comment by phase1geo** [comment] 2020-03-21 22:47
I'm wondering if the issue isn't with valac itself. Many times newer compilers tend to do more error checking than the older tools. I'm going to try building with a distro that supports the newer tools. It looks like you were using Fedora potentially, so I'll give that a try.

I always appreciate when people take the time to file issues. It makes software better.

**Comment by phase1geo** [comment] 2020-03-22 06:05
I have committed the fix for this issue to the `devel` branch if you would like to test it out. I attempted to figure out which version of libarchive changed which caused the issue. I picked 3.4.0 and later to compile the way that you need it to. Looks like Ubuntu 19.10 uses 3.4.0 which requires the changes to get it to compile as well. If anyone finds a slightly older version that doesn't work, I can always adjust this value in the `meson.build` file.

This change will be generally available in the next stable release which may be coming up pretty soon as I found another bug with 1.7.0 that I would like to fix.

**Comment by tim77** [comment] 2020-03-22 11:03
Tried with f6b63f51c5a02a129f99eb3334aacadbafec1ea5 from `devel` branch -- compiles fine!

**Comment by phase1geo** [comment] 2020-03-22 19:44
I have integrated this changed into the 1.7.1 stable release.

**Closed by phase1geo** 2020-03-22 19:44 UTC
Labels: bug, fixed
