### ISSUE TITLE
Node link to a child of folded node

### ISSUE THREAD

**Issue by wada3n** [phase1geo/Minder#199] opened 2020-08-17 11:42 UTC
I would like to note a simple issue, when there is a link between a node and another node found in folded node.
When clicking on the link, it does not move to that node, nor does it give any hint of where the link is.
I think the issue can be solved in two ways:
Either by unfold node, and its branches appear immediately after clicking on the link.
Or by showing a glow surrounding the parent node as an illustration of where the link is.

**Comment by phase1geo** [comment] 2020-08-17 13:37
The intended behavior should be that the node is made visible by unfolding itself.  I will get this fixed shortly.

**Comment by phase1geo** [comment] 2020-08-17 23:22
This should now be fixed in the devel branch and will be generally available in the next stable release.

**Closed** 2020-08-28 13:48 UTC
Labels: bug, fixed
