### ISSUE TITLE
Feedback from Ubuntu

### ISSUE THREAD

**Issue by yannicka** [phase1geo/Minder#16] opened 2018-07-27 21:35 UTC
I know you are alone to develop the software, I know that it is recent and I know it's a elementaryOS application, but I've only an Ubuntu 18.04, so I've installed your (good) software on my computer and I wanted to make a feedback:

- Key bindings does not works (no one)
- An Inkscape-like navigation would be good (I think): `wheel+click` to navigate, `ctrl+wheel(up/down)` to zoom/unzoom, `wheel+(up/down)` to go up and down, and `shift+wheel(up/down)` to go left and right
- Saving always ask me where I want to save the file instead of only do that on the first save
- Have the possibility to choose node layout for each node (or maybe only for each root node) and not only for the document (I think it's a big task, it's just an idea)
- Have an arrow on the node, to fold and unfold (and not a checkbox like now)
- I can select the title in the node, but I'm not able to edit the title

Anyway, thank you for the software.

**Comment by phase1geo** [comment] 2018-07-27 21:46
Thanks for the feedback!

I want to note two things you mentioned. First, the “save” button is really a “save as” button in elementary, thus the reason why you get the dialogue. Minder auto-saves all changes. If the document is unnamed by the user, it is auto-saved to your local library until you save it as a named file. Hopefully, that makes sense. Minder uses this approach to saving because the elementary OS HIG recommends that native apps do that. As such, this is the one feature that I won’t change from the list that you provided.

Second, the inability to detect key presses is an issue that one other user currently has filed. I can’t reproduce this problem on my end. Any help in better understanding why this doesn’t work would be greatly appreciated!

**Comment by phase1geo** [comment] 2018-07-27 21:48
One final note, the remaining requests I will take into consideration. Thanks again!

**Comment by yannicka** [comment] 2018-07-28 11:33
Thanks for information.

Regarding the key presses, those of MainWindow works, but those of DrawArea does not works.

I've try something on DrawArea, and replacing:

```vala
var nomod   = (e.state & ModifierType.MODIFIER_MASK) == 0;
var control = (e.state & ModifierType.MODIFIER_MASK) == ModifierType.CONTROL_MASK;
var shift   = (e.state & ModifierType.MODIFIER_MASK) == ModifierType.SHIFT_MASK;
```

by:

```vala
var control = (bool) e.state & ModifierType.CONTROL_MASK;
var shift   = (bool) e.state & ModifierType.SHIFT_MASK;
var nomod   = !(control || shift);
```

It works.

**Comment by lilumb** [comment] 2018-07-30 15:04
I've recently installed Minder via elementary OS's AppCenter. Sadly, none of the key bindings I've tried work for me either. How can we assist in debugging this? This is a showstopper for me at the moment. Otherwise, this app looks very nice!

**Comment by phase1geo** [comment] 2018-07-30 15:14
The bug related to key bindings has been resolved and will be a part of the next release which should be coming out very soon.

**Comment by phase1geo** [comment] 2018-08-06 17:14
I am going to close this issue out. I have the feature requests from this issue added to my internal feature request list.

**Closed by phase1geo** 2018-08-06 17:14 UTC
