### ISSUE TITLE
Property Sidebar > Style > Color Fill greyed out.

### ISSUE THREAD

**Issue by LifeWatcher123** [phase1geo/Minder#436] opened 2021-12-04 08:53 UTC
I'd like to change the color fill of particular nodes, but the option is greyed out. Am I missing something?

![Screenshot](https://user-images.githubusercontent.com/43345572/144703622-5877ea6f-a7e2-4dff-a9f0-a763b6e6cd2a.png)

**Comment by phase1geo** [comment] 2021-12-04 13:06
If a selected node is a root node or has a border type that is not "fillable" (these include _, [, and no border styles), the fill switch will be inactivated. This is by design and not considered to be a bug.

**Comment by LifeWatcher123** [comment] 2021-12-04 13:30
I see. That makes sense.

I will say, I think there should be a hint on how that works. A tooltip or some little text that shows below when disabled should do.

**Comment by phase1geo** [comment] 2021-12-21 04:13
I have added a tooltip to the node fill switch to explain the usage of the feature.  It has been committed to the master branch.

**Closed** 2022-01-22 04:39 UTC
Labels: enhancement, fixed
