### ISSUE TITLE
Searching for localized stickers fails

### ISSUE THREAD

**Issue by prokoudine** [phase1geo/Minder#374] opened 2021-06-27 13:15 UTC
Searching for localized stickers returns no results when the right words from an actual translation are used.

I'll do another translation PR for you to have something to test for, if you like.

**Comment by phase1geo** [comment] 2021-06-27 13:43
I don’t think the additional information will be needed. I know what the issue is and will get a fix in place soon.

**Comment by phase1geo** [comment] 2021-06-28 02:42
This issue should be fixed in the master branch.

**Closed** 2021-08-25 03:23 UTC
Labels: bug, fixed
