### ISSUE TITLE
Changing text of nodes doesn't work

### ISSUE THREAD

**Issue by jtrees** [phase1geo/Minder#13] opened 2018-07-19 08:13 UTC
* When I click on a node and attempt to edit the text in the canvas view nothing happens.
* If I edit the node title in the sidebar and then move focus to the canvas, the change I made to the title gets discarded.

**Comment by phase1geo** [comment] 2018-07-22 00:50
I have updated Minder to save node title changes properly whenever input focus is lost within the title entry field.

**Comment by jtrees** [comment] 2018-07-22 15:30
- Double clicking the node does put the node in what looks like an edit mode, but keyboard input has no effect for me.
- Selecting the node (with a single click) and pressing `e` does not put it in edit mode for me.
- Editing the node title in the sidebar and pressing `return` works.

**Comment by phase1geo** [comment] 2018-07-24 14:08
I have not been able to replicate this issue in the main branch thus far. I did make a small change to address a different issue that changes the input focus immediately when the left mouse button is clicked. I'm not sure if this is keeping me from replicating the issue.

I will leave this issue in the opened state when the next Minder release is made. If you could confirm that the issue is fixed or not after that happens, I will update this issue's state accordingly.

**Comment by jtrees** [comment] 2018-07-24 14:52
The issue still persists in the newest master build (9f6ba79065e8c925110c1e7f6ade3104edb12d1b).

**Comment by phase1geo** [comment] 2018-07-24 20:40
All of the actions you are describing in the last update to this bug do not require keyboard input focus to achieve. These actions are all implemented as mouse events.

Did you mention which OS you are using (Loki or Juno)?

**Comment by jtrees** [comment] 2018-07-25 07:44
Good point. Do you know how to figure out where the keyboard focus is?

I am still on Loki by the way.

**Comment by jtrees** [comment] 2018-07-25 14:21
Pressing tab has no effect when I'm "in the canvas". It does work to cycle through the sidebar controls though.

**Comment by phase1geo** [comment] 2018-07-28 13:45
Could you grab the latest version of the main branch and let me know if this issue is fixed or not?

**Comment by jtrees** [comment] 2018-07-30 07:32
Sweet! It works now. Thanks.

**Comment by phase1geo** [comment] 2018-07-30 07:35
Since we have confirmed that the latest version of the main branch is working, I'm closing this issue. It will be generally available in the next release of Minder in AppCenter.

**Closed by phase1geo** 2018-07-30 07:35 UTC
