### ISSUE TITLE
TODO status not inherited by all child nodes

### ISSUE THREAD

**Issue by prokoudine** [phase1geo/Minder#595] opened 2024-01-11 04:08 UTC
1. Create a node
2. Press T to toggle TODO status
3. Press TAB to create a child node
4. The child node is automatically created with TODO status on
5. Press ENTER to create a sibling node
6. None of the sibling nodes you create inherit the TODO status

![image](https://github.com/phase1geo/Minder/assets/57467/a8d7ee62-74b8-4b50-829a-71fbe5ebe644)

I'd expect all new child nodes of a node with TODO status enabled to inherit that. Am I wrong?

**Comment by phase1geo** [comment] 2024-01-13 02:41
I don't think this behavior was intended, so I'm labeling it as a bug and will get it fixed ASAP.

**Comment by phase1geo** [comment] 2024-01-13 03:43
I have committed a change to fix this issue.  If you get a chance, try this change out and feel free to test out task scenarios.  I don't think that I have broken any other task functionality with this change, but there's always the possibility ;)

**Closed** 2024-02-12 14:59 UTC
Labels: bug, fixed
