### ISSUE TITLE
Single node deleting causes the canvas to glitch out.

### ISSUE THREAD

**Issue by Visualvengeance** [phase1geo/Minder#281] opened 2021-01-27 07:28 UTC
Reproducing:

Delete single node which has child nodes, then undo the action. This seems to make the canvas glitch out in a way that the formerly deleted node's children seem to get glued onto the camera and move together with the canvas.

**Comment by phase1geo** [comment] 2021-02-01 01:10
Are you seeing this problem in the devel branch?  I am unable to reproduce this issue in the devel branch.

**Comment by Visualvengeance** [comment] 2021-02-02 03:21
Yes, this seems to persist for me in the devel branch too, no idea what this is caused by though.

**Comment by phase1geo** [comment] 2021-02-03 07:02
Is there anything interesting about the subtree being deleted?

- Are any children folded?
- Are there any connections between child nodes and other nodes?
- What layout is the tree using?

Any chance that you could attach a short screencast of the issue?

**Comment by Visualvengeance** [comment] 2021-02-03 15:40
The deleted node's subtree only has basic nodes, without tasks, notes, images etc

No children are being folded.
No connections between child nodes and other nodes.
The tree is using the "upward" layout, but this seems to happen in all of the layouts.

Moving and dragging the effected node "pops" the node into its original place, moving children nodes makes it worse since the moved child stops moving together with the canvas while the unmoved children keep moving with the canvas.


https://user-images.githubusercontent.com/23021041/106770557-64cb9080-663e-11eb-8315-40ea09f09b68.mp4

**Comment by phase1geo** [comment] 2021-02-04 04:43
Ah! The screen captures helped me out on this one. I missed the fact that you chose the "Delete Single Node".  I was just using "Delete" with a single node selected.

I can replicate this problem now, so I'll get to work on it immediately.

**Comment by phase1geo** [comment] 2021-02-04 05:53
I believe that I have this issue fixed in the devel branch which will be generally available in the next stable release.  Feel free to grab the latest devel branch and verify that the issue is resolved.

**Comment by Visualvengeance** [comment] 2021-02-04 22:28
Yes, sorry for not being more precise! 

I will upgrade to the latest version of devel branch and test it. Thank you for your excellent work!

**Closed** 2021-02-11 03:28 UTC
Labels: bug, fixed
