### ISSUE TITLE
central nodenote modifying causes instant crash (1.15.1)

### ISSUE THREAD

**Issue by goldanorak** [phase1geo/Minder#563] opened 2023-08-18 17:26 UTC
Hello (running Minder 1.15.1 into linux mint 21.2; cinnamon environment version 5.8.4.) I've just noticed that modifying or adding "nodenote" to the central node ... instantly crashes Minder ... with no way of reopening the mindmap without crashing directly. Tried to remove the nodenotes, replacing by : `<nodenote></nodenote>` This has led to a small improvement : the mindmap file opens without crashing Minder, but nothing is displayed, white everywhere (update : i meanwhile noticed that the "completely blank" problem could be a zoom/centering bug, described elsewhere here ; maybe it was). The initial crash occurred when I tried to modify the nodenote of the central node; Minder crashed and then the file could no longer be opened without crashing Minder (with later the slight progress I described above) I've tried again with another new empty file : when i add nodenote to de secondary nodes, no problem, but adding or modifying the central node causes crash.

**Comment by goldanorak** [comment] 2023-08-18 17:40
... tried to remove the nodenotes, replacing by "<nodenote></nodenote>". This has led to a small improvement : the mindmap file opens without crashing Minder, but nothing is displayed (white everywhere).

**Comment by goldanorak** [comment] 2023-08-18 18:07
I've tried again with another new empty file: add nodes then add nodenotes, and this time it works without a problem. So the other file must be corrupted somehow, but I don't see how. The initial crash occurred when I tried to modify the nodenote of the central node; Minder crashed and then the file could no longer be opened without crashing Minder (with later the slight progress I described above). I suppose the bug will be difficult to reproduce, but I hope these explanations will be useful to the developpement.

**Comment by phase1geo** [comment] 2023-08-22 21:14
This issue should be fixed in releases beyond 1.15.1, I believe.  I'm working on trying to get a Flathub package available with the contents of 1.15.3.  I don't know where Linux Mint pulls its packages from, but I'm hoping that it has Flathub integration in some fashion.

**Comment by goldanorak** [comment] 2023-08-24 08:14
Mintinstall (mint app store) just added the 1-15-5 version in flatpak today. Tested for the bug explained above, but it's still there. I name the central node, the enter a nodenote for it, then click elsewhere in the main window and minder immediately crashes.

**Comment by phase1geo** [comment] 2023-08-24 15:31
I can't reproduce this using the 1.15.5 elementary OS Flatpak or the Flathub Flatpak versions.  I have a Fedora installation that I can try with the Flatpak.

**Comment by phase1geo** [comment] 2023-08-24 15:42
I can't reproduce it on Fedora using the Flathub flatpak either.

**Comment by phase1geo** [comment] 2023-08-24 16:51
Okay, I actually was able to replicate this issue.  The key was to have the node fill style option enabled when creating the note.

I have this fixed in the master branch.  You could work around this problem by deselecting the node fill style option for the map.  Not ideal (of course), but it should keep things up and running for you in the meantime.

**Closed** 2023-09-20 04:30 UTC
Labels: bug, fixed
