### ISSUE TITLE
crash while launch

### ISSUE THREAD

**Issue by superiums** [phase1geo/Minder#328] opened 2021-04-14 10:36 UTC
crash while launch,  happens afer upgrade in theses two moths. (reinstall not work)

version: 1.12.0
os: arch Linux

it reports:
``` bash
I/O warning : failed to load external entity "/home/user/.local/share/minder/favorites.xml"
I/O warning : failed to load external entity "/home/user/.local/share/minder/exports.xml"
free(): invalid pointer
fish: Job 1, 'com.github.phase1geo.minder' terminated by signal SIGABRT (Abort)
```

**Comment by phase1geo** [comment] 2021-04-15 03:17
This is a duplicate issue of #318

**Comment by phase1geo** [comment] 2021-04-15 03:19
BTW, I have just submitted a fix to the master branch for that issue.  If you would like to build Minder from the GitHub master branch to verify the issue is fixed, I will close this issue.

**Comment by phase1geo** [comment] 2021-04-16 11:55
I have released 1.12.1 that should fix this issue. Closing bug.

**Closed by phase1geo** 2021-04-16 11:55 UTC
Labels: duplicate
