### ISSUE TITLE
when selecting several nodes one cannot drag and drop the selected set

### ISSUE THREAD

**Issue by daveiro** [phase1geo/Minder#268] opened 2021-01-01 21:46 UTC
the expected behavior (happening in freemind/freeplane) is that: while clicking on one of the nodes in the selection, one can drag all of the selected nodes to a new parent or just change their relative position to some other place in the middle of their siblings; what currently happens is that the selection is lost and just the clicked node is selected

**Comment by daveiro** [comment] 2021-01-01 22:21
sorry I noticed now this is a duplicate of issue #243 so this can be deleted/removed

**Comment by phase1geo** [comment] 2021-02-14 03:08
Since this is a duplicate of #243, I'm going to close out the issue just to clean things up.  Keep in mind that #243 is not closed at this point.

**Closed by phase1geo** 2021-02-14 03:08 UTC
Labels: duplicate
