### ISSUE TITLE
Minder crashes when i change themes 

### ISSUE THREAD

**Issue by MartineMin** [phase1geo/Minder#335] opened 2021-04-19 12:33 UTC
I create a new document. I modify the color of the node for example. I save the document and then i can't open it never. 
[teste1.zip](https://github.com/phase1geo/Minder/files/6336070/teste1.zip).
So  I can't modify the styles of my mindmapping

**Comment by phase1geo** [comment] 2021-04-22 20:40
This file looks like it comes from an older version of Minder.  What version are you running?

**Comment by phase1geo** [comment] 2021-04-23 00:54
Okay, I see that the issue is due to loading an old Minder file into the latest (or later) version of Minder.  I can replicate the issue so I will get this fixed and update the issue shortly.

**Comment by phase1geo** [comment] 2021-04-23 02:04
This issue should now be fixed in the master branch and will be generally available in the 1.12.2 release.

**Comment by MartineMin** [comment] 2021-04-23 05:02
I have ubuntu 20.04. 2 and i use minder 1.5.1-1. How could have I the 1.12.2 release ? 
thank-you very much for your reactivity. 
Have a good day

**Comment by phase1geo** [comment] 2021-04-23 11:55
You should be able to download the source from GitHub, build and run it, if you choose to.

**Closed** 2021-04-23 16:41 UTC
Labels: bug, fixed
