### ISSUE TITLE
Minder crashes when disable animations, then enable it again and press one of the nodes

### ISSUE THREAD

**Issue by wada3n** [phase1geo/Minder#149] opened 2020-06-02 18:50 UTC
The app crashes when switch off (Enable animations), and choose one of the nodes, then switch on (enable animations) and choosing one of the nodes again.

By the way, I know this is embarrassing, but I didn't understand exactly what this "Enable Animation" button does.
same for Rotate main branch colors.

**Comment by phase1geo** [comment] 2020-06-02 19:36
The “enable animations” switch, when enabled, just animates node movement when the contents of the map changes. This is really just a preference switch. If there is some sort of problem with animations or the user just hates them, they can turn it off with the switch. There shouldn’t be a need to change this behavior most of the time, but if you have a really large mind-map such that the animation process causes the tool to become sluggish, disabling this feature is a quick way to remove this lag.

The “rotate main branch colors” feature, when enabled, will automatically assign a new color from the themes set of link colors whenever a new main branch is created off of a root node. You can disable this which will reuse the last used color for the new main branch. Again, probably not a feature that you will mess around with often, but for some users (it was a user-requested feature) this is helpful to more quickly control the colors used in the tree.

**Comment by wada3n** [comment] 2020-06-02 19:48
Okay. I got it.
Each feature has its own sophisticated work.
I liked the attention to detail and it is really very helpful.
I am thinking of creating an entire app wiki so that I can help you further spread it
Yesterday I found a video on YouTube that shows some of the features of the app after it was published on flathub and everyone liked it.

**Comment by phase1geo** [comment] 2020-06-03 15:01
I am unable to reproduce this error. The animation enable only affects nodes that are moved, not selected. Are you sure that the application crashed as a result of a selection and not a move? I’m going to need some help recreating the issue.

**Comment by wada3n** [comment] 2020-06-03 15:33
Yes the problem recurs with me, I tried this on Ubuntu and Elementary
When it is turned off and on again, the problem appears.
The app crashes with this message:
`Segmentation fault (core dumped)`

![Peek 2020-06-03 16-29](https://user-images.githubusercontent.com/13304792/83656730-ce7b3280-a5b7-11ea-8447-e6f936be0b4b.gif)

**Comment by phase1geo** [comment] 2020-06-03 15:35
Very useful. Thanks for the screen recording. I’ll give it a go.

**Comment by wada3n** [comment] 2020-06-03 15:53
Thank you very much for all your hard work and dedication; 
by the way, there is something you can see it in the picture
Whenever a new tab is added, a spinner appears at the top, stays there all the time.
![2020-06-03_16-47](https://user-images.githubusercontent.com/13304792/83658431-1ac77200-a5ba-11ea-98bc-f4158f231455.png)
The problem has only appeared in Ubuntu, not in elementary os

**Comment by phase1geo** [comment] 2020-06-04 03:28
The application crash issue has been fixed in the devel branch and will be generally available in the next stable release.

**Comment by wada3n** [comment] 2020-06-04 13:01
I can confirm that.
You are doing amazing work in very little time!
thank you.

**Closed** 2020-07-02 04:33 UTC
Labels: bug, fixed
